
BEGIN;

SET search_path = 'sift';

DROP FUNCTION IF EXISTS GetRandomTaskID(BIGINT[]);
CREATE FUNCTION GetRandomTaskID(_ExceptTaskID BIGINT[] DEFAULT NULL) 
RETURNS BIGINT AS
$$
  SELECT TaskID 
  FROM Task
  WHERE _ExceptTaskID IS NULL 
    OR TaskID != ANY(_ExceptTaskID)
  LIMIT 1;
$$ LANGUAGE SQL;


DROP FUNCTION IF EXISTS GetRandomAlertID();
CREATE FUNCTION GetRandomAlertID() 
RETURNS BIGINT AS
$$
  SELECT AlertID 
  FROM Alert
  ORDER BY RANDOM()
  LIMIT 1;
$$ LANGUAGE SQL;


DROP FUNCTION IF EXISTS GetRandomPlaceID();
CREATE FUNCTION GetRandomPlaceID() 
RETURNS BIGINT AS
$$
  SELECT PlaceID 
  FROM Place
  ORDER BY RANDOM()
  LIMIT 1;
$$ LANGUAGE SQL;


DROP FUNCTION IF EXISTS GetRandomInterval();
CREATE FUNCTION GetRandomInterval() 
RETURNS INTERVAL AS
$$
  SELECT (a || ' hour')::INTERVAL 
  FROM generate_series(1, 24) as e(a)
  ORDER BY RANDOM()
  LIMIT 1;
$$ LANGUAGE SQL;


COMMIT;
